services:
  app:
    image: rafadanam/cf22-api:${IMAGE_TAG}
    container_name: cf22-api
    restart: always
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    ports:
      - '5500:${APP_PORT}'
    volumes:
      - db_data:/usr/app/db_data
      - live_data:/usr/app/live_data
volumes:
  db_data:
  live_data:
